#+title: readme 
#+Author: daoyi
#+date: 2022-02-05T12:04:10+08:00
#+comment: false
#+tags: 
#+categories: hugo 

* about

use =emacs + hugo= deploy static blog on  =Github Pages= .

* Hugo

** theme

Configuration include two themes:
- even
  config-even.toml
- loveit
  config-loveit.toml

Choose one of themes configration.

=cp config-xxx.toml config.toml=.

Then generate static web-files:
- =hugo= (default config.toml)
- =hugo --config config-xxx.toml=

** notes
- post

  If even theme, blog source files must be saved in content/post, or can't show content on homepage of site(daotoyi.cn).

  Can creat link =post/= to /posts/=, loveit theme can show hogmepgae normally.

- archetypes/default

  **Must configrate archetypes/default.md(org) match with theme used, or hugo will generate error.**
  
* utterance
  utterance hot comments on blog based on  github-pages.

- repository
  Create public repo on github for store comments of blog.

- configuration
  - config.toml
    
  Add below content in config.toml：

#+begin_src toml
  [params.utter]
    repo = "{githubName}/{repoName}"
    issueTerm = "title"        #set name of issue match every blog，option: pathname/title/url
    theme = "github-light"
#+end_src


  - comments
    add below content in themes/even/layouts/partials/comments.html，postion: after gitalk：

#+begin_src html
  {{- if .Site.Params.utter.repo -}}
    <div id="utter-container"></div>
    <script src="https://utteranc.es/client.js"
        repo= '{{ .Site.Params.utter.repo }}'
        issue-term= "{{ .Site.Params.utter.issueTerm }}"
        theme= '{{ .Site.Params.utter.theme }}'
        crossorigin= "anonymous"
        async>
    </script> 
  {{- end }}
#+end_src

* Github Action

After =git push=, automatic generate static web-fiels, deploy on Github && sync an deploy Gitee Pages.

action configure in =.github/workflows/main.yml=
